name: capstone
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39hd77b12b_7
  - ca-certificates=2023.11.17=h56e8100_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py39h2bbff1b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.3=py39h89fc84f_0
  - cuda-cccl=12.3.101=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - faiss=1.7.4=py39h2eb4301_0_cpu
  - filelock=3.9.0=py39haa95532_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - idna=3.4=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.2=py39haa95532_0
  - jpeg=9e=h2bbff1b_1
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.4.101=0
  - libcurand-dev=10.3.4.101=0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=h2bbff1b_1
  - libfaiss=1.7.4=hba6d9cf_0_cpu
  - libfaiss-avx2=1.7.4=h1234567_0_cpu
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.1=py39h2bbff1b_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.8=py39h2bbff1b_0
  - mkl_random=1.2.4=py39h59b6b97_0
  - mpmath=1.3.0=py39haa95532_0
  - msys2-conda-epoch=20160418=1
  - networkx=3.1=py39haa95532_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.1.4=hcfcfb64_0
  - pillow=10.0.1=py39h045eedc_0
  - pip=23.3=py39haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py39haa95532_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.18=h1aa4202_0
  - python-dotenv=1.0.0=pyhd8ed1ab_1
  - python_abi=3.9=2_cp39
  - pytorch=2.0.1=py3.9_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-mutex=1.0=cuda
  - requests=2.31.0=py39haa95532_0
  - setuptools=68.0.0=py39haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - sympy=1.11.1=py39haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - typing_extensions=4.7.1=py39haa95532_0
  - tzdata=2023c=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=1.26.18=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.36.32532=hdcecf7f_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wheel=0.41.2=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - aiofiles==23.2.1
      - antlr4-python3-runtime==4.8
      - audioread==3.0.1
      - av==11.0.0
      - bitarray==2.8.3
      - cachetools==5.3.2
      - colorama==0.4.6
      - cython==3.0.5
      - decorator==5.1.1
      - fairseq==0.12.2
      - google-api-core==2.14.0
      - google-auth==2.23.4
      - google-cloud-core==2.3.3
      - google-cloud-speech==2.22.0
      - google-cloud-storage==2.13.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.6.0
      - googleapis-common-protos==1.61.0
      - grpcio==1.59.3
      - grpcio-status==1.59.3
      - hydra-core==1.0.7
      - joblib==1.3.2
      - lazy-loader==0.3
      - librosa==0.10.1
      - llvmlite==0.41.1
      - lxml==4.9.3
      - msgpack==1.0.7
      - numba==0.58.1
      - numpy==1.26.2
      - omegaconf==2.0.6
      - packaging==23.2
      - platformdirs==4.0.0
      - pooch==1.8.0
      - portalocker==2.8.2
      - praat-parselmouth==0.4.3
      - proto-plus==1.22.3
      - protobuf==4.25.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydub==0.25.1
      - pywin32==306
      - pyworld==0.3.4
      - pyyaml==6.0.1
      - regex==2023.10.3
      - resampy==0.4.2
      - rsa==4.9
      - sacrebleu==2.3.2
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - soundfile==0.12.1
      - soxr==0.3.7
      - tabulate==0.9.0
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.2.0
      - torchaudio==2.0.2
      - torchcrepe==0.0.22
      - torchvision==0.15.2
      - tqdm==4.66.1
      - websockets==12.0
prefix: C:\Users\jyoo\anaconda3\envs\capstone
